#!/usr/bin/env bash

rm -rf /opt/pt
rm -f /usr/share/icons/gnome/48x48/mimetypes/pk{a,t,z}.png
rm -f /usr/share/mime/packages/cisco-pk{a,t,z}/xml
rm -f /usr/share/applications/cisco-{pt,ptsa}7.desktop

update-desktop-database /usr/share/applications
#gtk-update-icon-cache /usr/share/icons/hicolor

unlink /usr/local/bin/packettracer

echo -e "\e[40;93mfinished uninstalling.\e[0m"
